/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Campaign service. Represents a row in the &quot;Newsletter_Campaign&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.newsletter.model.impl.CampaignModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.newsletter.model.impl.CampaignImpl}.
 * </p>
 *
 * @author Bruno Pinheiro
 * @see Campaign
 * @see com.liferay.newsletter.model.impl.CampaignImpl
 * @see com.liferay.newsletter.model.impl.CampaignModelImpl
 * @generated
 */
public interface CampaignModel extends BaseModel<Campaign> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a campaign model instance should use the {@link Campaign} interface instead.
	 */

	/**
	 * Gets the primary key of this campaign.
	 *
	 * @return the primary key of this campaign
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this campaign
	 *
	 * @param pk the primary key of this campaign
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the uuid of this campaign.
	 *
	 * @return the uuid of this campaign
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this campaign.
	 *
	 * @param uuid the uuid of this campaign
	 */
	public void setUuid(String uuid);

	/**
	 * Gets the campaign ID of this campaign.
	 *
	 * @return the campaign ID of this campaign
	 */
	public long getCampaignId();

	/**
	 * Sets the campaign ID of this campaign.
	 *
	 * @param campaignId the campaign ID of this campaign
	 */
	public void setCampaignId(long campaignId);

	/**
	 * Gets the send date of this campaign.
	 *
	 * @return the send date of this campaign
	 */
	public Date getSendDate();

	/**
	 * Sets the send date of this campaign.
	 *
	 * @param sendDate the send date of this campaign
	 */
	public void setSendDate(Date sendDate);

	/**
	 * Gets the email subject of this campaign.
	 *
	 * @return the email subject of this campaign
	 */
	@AutoEscape
	public String getEmailSubject();

	/**
	 * Sets the email subject of this campaign.
	 *
	 * @param emailSubject the email subject of this campaign
	 */
	public void setEmailSubject(String emailSubject);

	/**
	 * Gets the sender name of this campaign.
	 *
	 * @return the sender name of this campaign
	 */
	@AutoEscape
	public String getSenderName();

	/**
	 * Sets the sender name of this campaign.
	 *
	 * @param senderName the sender name of this campaign
	 */
	public void setSenderName(String senderName);

	/**
	 * Gets the sender email of this campaign.
	 *
	 * @return the sender email of this campaign
	 */
	@AutoEscape
	public String getSenderEmail();

	/**
	 * Sets the sender email of this campaign.
	 *
	 * @param senderEmail the sender email of this campaign
	 */
	public void setSenderEmail(String senderEmail);

	/**
	 * Gets the content of this campaign.
	 *
	 * @return the content of this campaign
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this campaign.
	 *
	 * @param content the content of this campaign
	 */
	public void setContent(String content);

	/**
	 * Gets the sent of this campaign.
	 *
	 * @return the sent of this campaign
	 */
	public boolean getSent();

	/**
	 * Determines if this campaign is sent.
	 *
	 * @return <code>true</code> if this campaign is sent; <code>false</code> otherwise
	 */
	public boolean isSent();

	/**
	 * Sets whether this campaign is sent.
	 *
	 * @param sent the sent of this campaign
	 */
	public void setSent(boolean sent);

	/**
	 * Gets the campaign content ID of this campaign.
	 *
	 * @return the campaign content ID of this campaign
	 */
	public long getCampaignContentId();

	/**
	 * Sets the campaign content ID of this campaign.
	 *
	 * @param campaignContentId the campaign content ID of this campaign
	 */
	public void setCampaignContentId(long campaignContentId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Campaign campaign);

	public int hashCode();

	public Campaign toEscapedModel();

	public String toString();

	public String toXmlString();
}