package com.liferay.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Campaign service. Represents a row in the &quot;Newsletter_Campaign&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.newsletter.model.impl.CampaignModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.newsletter.model.impl.CampaignImpl}.
 * </p>
 *
 * @author Bruno Pinheiro
 * @see Campaign
 * @see com.liferay.newsletter.model.impl.CampaignImpl
 * @see com.liferay.newsletter.model.impl.CampaignModelImpl
 * @generated
 */
public interface CampaignModel extends BaseModel<Campaign> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a campaign model instance should use the {@link Campaign} interface instead.
     */

    /**
     * Gets the primary key of this campaign.
     *
     * @return the primary key of this campaign
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this campaign
     *
     * @param pk the primary key of this campaign
     */
    public void setPrimaryKey(long pk);

    /**
     * Gets the uuid of this campaign.
     *
     * @return the uuid of this campaign
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this campaign.
     *
     * @param uuid the uuid of this campaign
     */
    public void setUuid(String uuid);

    /**
     * Gets the campaign id of this campaign.
     *
     * @return the campaign id of this campaign
     */
    public long getCampaignId();

    /**
     * Sets the campaign id of this campaign.
     *
     * @param campaignId the campaign id of this campaign
     */
    public void setCampaignId(long campaignId);

    /**
     * Gets the title of this campaign.
     *
     * @return the title of this campaign
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this campaign.
     *
     * @param title the title of this campaign
     */
    public void setTitle(String title);

    /**
     * Gets the content of this campaign.
     *
     * @return the content of this campaign
     */
    @AutoEscape
    public String getContent();

    /**
     * Sets the content of this campaign.
     *
     * @param content the content of this campaign
     */
    public void setContent(String content);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public void setEscapedModel(boolean escapedModel);

    public Serializable getPrimaryKeyObj();

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Campaign campaign);

    public int hashCode();

    public Campaign toEscapedModel();

    public String toString();

    public String toXmlString();
}
