package com.liferay.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Contact service. Represents a row in the &quot;Newsletter_Contact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.newsletter.model.impl.ContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.newsletter.model.impl.ContactImpl}.
 * </p>
 *
 * @author Bruno Pinheiro
 * @see Contact
 * @see com.liferay.newsletter.model.impl.ContactImpl
 * @see com.liferay.newsletter.model.impl.ContactModelImpl
 * @generated
 */
public interface ContactModel extends BaseModel<Contact> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a contact model instance should use the {@link Contact} interface instead.
     */

    /**
     * Gets the primary key of this contact.
     *
     * @return the primary key of this contact
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this contact
     *
     * @param pk the primary key of this contact
     */
    public void setPrimaryKey(long pk);

    /**
     * Gets the uuid of this contact.
     *
     * @return the uuid of this contact
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this contact.
     *
     * @param uuid the uuid of this contact
     */
    public void setUuid(String uuid);

    /**
     * Gets the contact id of this contact.
     *
     * @return the contact id of this contact
     */
    public long getContactId();

    /**
     * Sets the contact id of this contact.
     *
     * @param contactId the contact id of this contact
     */
    public void setContactId(long contactId);

    /**
     * Gets the email of this contact.
     *
     * @return the email of this contact
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this contact.
     *
     * @param email the email of this contact
     */
    public void setEmail(String email);

    /**
     * Gets the name of this contact.
     *
     * @return the name of this contact
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this contact.
     *
     * @param name the name of this contact
     */
    public void setName(String name);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public void setEscapedModel(boolean escapedModel);

    public Serializable getPrimaryKeyObj();

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(Contact contact);

    public int hashCode();

    public Contact toEscapedModel();

    public String toString();

    public String toXmlString();
}
