package com.liferay.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the NewsletterLog service. Represents a row in the &quot;Newsletter_NewsletterLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.newsletter.model.impl.NewsletterLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.newsletter.model.impl.NewsletterLogImpl}.
 * </p>
 *
 * @author Bruno Pinheiro
 * @see NewsletterLog
 * @see com.liferay.newsletter.model.impl.NewsletterLogImpl
 * @see com.liferay.newsletter.model.impl.NewsletterLogModelImpl
 * @generated
 */
public interface NewsletterLogModel extends BaseModel<NewsletterLog> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a newsletter log model instance should use the {@link NewsletterLog} interface instead.
     */

    /**
     * Gets the primary key of this newsletter log.
     *
     * @return the primary key of this newsletter log
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this newsletter log
     *
     * @param pk the primary key of this newsletter log
     */
    public void setPrimaryKey(long pk);

    /**
     * Gets the uuid of this newsletter log.
     *
     * @return the uuid of this newsletter log
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this newsletter log.
     *
     * @param uuid the uuid of this newsletter log
     */
    public void setUuid(String uuid);

    /**
     * Gets the newsletter log id of this newsletter log.
     *
     * @return the newsletter log id of this newsletter log
     */
    public long getNewsletterLogId();

    /**
     * Sets the newsletter log id of this newsletter log.
     *
     * @param newsletterLogId the newsletter log id of this newsletter log
     */
    public void setNewsletterLogId(long newsletterLogId);

    /**
     * Gets the send campaign id of this newsletter log.
     *
     * @return the send campaign id of this newsletter log
     */
    public long getSendCampaignId();

    /**
     * Sets the send campaign id of this newsletter log.
     *
     * @param sendCampaignId the send campaign id of this newsletter log
     */
    public void setSendCampaignId(long sendCampaignId);

    /**
     * Gets the contact id of this newsletter log.
     *
     * @return the contact id of this newsletter log
     */
    public long getContactId();

    /**
     * Sets the contact id of this newsletter log.
     *
     * @param contactId the contact id of this newsletter log
     */
    public void setContactId(long contactId);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public void setEscapedModel(boolean escapedModel);

    public Serializable getPrimaryKeyObj();

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(NewsletterLog newsletterLog);

    public int hashCode();

    public NewsletterLog toEscapedModel();

    public String toString();

    public String toXmlString();
}
