/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the NewsletterCampaign service. Represents a row in the &quot;Newsletter_NewsletterCampaign&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.newsletter.model.impl.NewsletterCampaignModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.newsletter.model.impl.NewsletterCampaignImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewsletterCampaign
 * @see com.liferay.newsletter.model.impl.NewsletterCampaignImpl
 * @see com.liferay.newsletter.model.impl.NewsletterCampaignModelImpl
 * @generated
 */
public interface NewsletterCampaignModel extends BaseModel<NewsletterCampaign>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a newsletter campaign model instance should use the {@link NewsletterCampaign} interface instead.
	 */

	/**
	 * Returns the primary key of this newsletter campaign.
	 *
	 * @return the primary key of this newsletter campaign
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this newsletter campaign.
	 *
	 * @param primaryKey the primary key of this newsletter campaign
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this newsletter campaign.
	 *
	 * @return the uuid of this newsletter campaign
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this newsletter campaign.
	 *
	 * @param uuid the uuid of this newsletter campaign
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the campaign ID of this newsletter campaign.
	 *
	 * @return the campaign ID of this newsletter campaign
	 */
	public long getCampaignId();

	/**
	 * Sets the campaign ID of this newsletter campaign.
	 *
	 * @param campaignId the campaign ID of this newsletter campaign
	 */
	public void setCampaignId(long campaignId);

	/**
	 * Returns the group ID of this newsletter campaign.
	 *
	 * @return the group ID of this newsletter campaign
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this newsletter campaign.
	 *
	 * @param groupId the group ID of this newsletter campaign
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this newsletter campaign.
	 *
	 * @return the company ID of this newsletter campaign
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this newsletter campaign.
	 *
	 * @param companyId the company ID of this newsletter campaign
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this newsletter campaign.
	 *
	 * @return the user ID of this newsletter campaign
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this newsletter campaign.
	 *
	 * @param userId the user ID of this newsletter campaign
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this newsletter campaign.
	 *
	 * @return the user uuid of this newsletter campaign
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this newsletter campaign.
	 *
	 * @param userUuid the user uuid of this newsletter campaign
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this newsletter campaign.
	 *
	 * @return the user name of this newsletter campaign
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this newsletter campaign.
	 *
	 * @param userName the user name of this newsletter campaign
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this newsletter campaign.
	 *
	 * @return the create date of this newsletter campaign
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this newsletter campaign.
	 *
	 * @param createDate the create date of this newsletter campaign
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this newsletter campaign.
	 *
	 * @return the modified date of this newsletter campaign
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this newsletter campaign.
	 *
	 * @param modifiedDate the modified date of this newsletter campaign
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the content ID of this newsletter campaign.
	 *
	 * @return the content ID of this newsletter campaign
	 */
	public long getContentId();

	/**
	 * Sets the content ID of this newsletter campaign.
	 *
	 * @param contentId the content ID of this newsletter campaign
	 */
	public void setContentId(long contentId);

	/**
	 * Returns the email subject of this newsletter campaign.
	 *
	 * @return the email subject of this newsletter campaign
	 */
	@AutoEscape
	public String getEmailSubject();

	/**
	 * Sets the email subject of this newsletter campaign.
	 *
	 * @param emailSubject the email subject of this newsletter campaign
	 */
	public void setEmailSubject(String emailSubject);

	/**
	 * Returns the sender email of this newsletter campaign.
	 *
	 * @return the sender email of this newsletter campaign
	 */
	@AutoEscape
	public String getSenderEmail();

	/**
	 * Sets the sender email of this newsletter campaign.
	 *
	 * @param senderEmail the sender email of this newsletter campaign
	 */
	public void setSenderEmail(String senderEmail);

	/**
	 * Returns the sender name of this newsletter campaign.
	 *
	 * @return the sender name of this newsletter campaign
	 */
	@AutoEscape
	public String getSenderName();

	/**
	 * Sets the sender name of this newsletter campaign.
	 *
	 * @param senderName the sender name of this newsletter campaign
	 */
	public void setSenderName(String senderName);

	/**
	 * Returns the sent of this newsletter campaign.
	 *
	 * @return the sent of this newsletter campaign
	 */
	public boolean getSent();

	/**
	 * Returns <code>true</code> if this newsletter campaign is sent.
	 *
	 * @return <code>true</code> if this newsletter campaign is sent; <code>false</code> otherwise
	 */
	public boolean isSent();

	/**
	 * Sets whether this newsletter campaign is sent.
	 *
	 * @param sent the sent of this newsletter campaign
	 */
	public void setSent(boolean sent);

	/**
	 * Returns the sent date of this newsletter campaign.
	 *
	 * @return the sent date of this newsletter campaign
	 */
	public Date getSentDate();

	/**
	 * Sets the sent date of this newsletter campaign.
	 *
	 * @param sentDate the sent date of this newsletter campaign
	 */
	public void setSentDate(Date sentDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(NewsletterCampaign newsletterCampaign);

	public int hashCode();

	public CacheModel<NewsletterCampaign> toCacheModel();

	public NewsletterCampaign toEscapedModel();

	public String toString();

	public String toXmlString();
}