/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the NewsletterContent service. Represents a row in the &quot;Newsletter_NewsletterContent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.newsletter.model.impl.NewsletterContentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.newsletter.model.impl.NewsletterContentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewsletterContent
 * @see com.liferay.newsletter.model.impl.NewsletterContentImpl
 * @see com.liferay.newsletter.model.impl.NewsletterContentModelImpl
 * @generated
 */
public interface NewsletterContentModel extends BaseModel<NewsletterContent>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a newsletter content model instance should use the {@link NewsletterContent} interface instead.
	 */

	/**
	 * Returns the primary key of this newsletter content.
	 *
	 * @return the primary key of this newsletter content
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this newsletter content.
	 *
	 * @param primaryKey the primary key of this newsletter content
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this newsletter content.
	 *
	 * @return the uuid of this newsletter content
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this newsletter content.
	 *
	 * @param uuid the uuid of this newsletter content
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the content ID of this newsletter content.
	 *
	 * @return the content ID of this newsletter content
	 */
	public long getContentId();

	/**
	 * Sets the content ID of this newsletter content.
	 *
	 * @param contentId the content ID of this newsletter content
	 */
	public void setContentId(long contentId);

	/**
	 * Returns the group ID of this newsletter content.
	 *
	 * @return the group ID of this newsletter content
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this newsletter content.
	 *
	 * @param groupId the group ID of this newsletter content
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this newsletter content.
	 *
	 * @return the company ID of this newsletter content
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this newsletter content.
	 *
	 * @param companyId the company ID of this newsletter content
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this newsletter content.
	 *
	 * @return the user ID of this newsletter content
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this newsletter content.
	 *
	 * @param userId the user ID of this newsletter content
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this newsletter content.
	 *
	 * @return the user uuid of this newsletter content
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this newsletter content.
	 *
	 * @param userUuid the user uuid of this newsletter content
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this newsletter content.
	 *
	 * @return the user name of this newsletter content
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this newsletter content.
	 *
	 * @param userName the user name of this newsletter content
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this newsletter content.
	 *
	 * @return the create date of this newsletter content
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this newsletter content.
	 *
	 * @param createDate the create date of this newsletter content
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this newsletter content.
	 *
	 * @return the modified date of this newsletter content
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this newsletter content.
	 *
	 * @param modifiedDate the modified date of this newsletter content
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this newsletter content.
	 *
	 * @return the title of this newsletter content
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this newsletter content.
	 *
	 * @param title the title of this newsletter content
	 */
	public void setTitle(String title);

	/**
	 * Returns the content of this newsletter content.
	 *
	 * @return the content of this newsletter content
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this newsletter content.
	 *
	 * @param content the content of this newsletter content
	 */
	public void setContent(String content);

	/**
	 * Returns the article ID of this newsletter content.
	 *
	 * @return the article ID of this newsletter content
	 */
	public long getArticleId();

	/**
	 * Sets the article ID of this newsletter content.
	 *
	 * @param articleId the article ID of this newsletter content
	 */
	public void setArticleId(long articleId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(NewsletterContent newsletterContent);

	public int hashCode();

	public CacheModel<NewsletterContent> toCacheModel();

	public NewsletterContent toEscapedModel();

	public String toString();

	public String toXmlString();
}